const STORE='witnessJournal.v1';
const TAGS=[
 {id:'recognition',name:'Who recognises awareness?',desc:'Look at the knowing itself without quickly making a knower.'},
 {id:'direct',name:'Direct knowing',desc:'Distinguish immediate seeing, feeling and hearing from ideas about experience.'},
 {id:'witness',name:'Seer and ego',desc:'Notice the witness or seer language, and what the “I” and “me” try to own.'},
 {id:'shiva-shakti',name:'Shiva and Shakti',desc:'Explore awareness and its power in Kashmir Shaivism as a living question.'},
 {id:'nobody',name:'Nobody · nothing · wanting nothing',desc:'Hold the phrase lightly and test it in ordinary experience.'},
 {id:'gauri-shankar',name:'Gauri Shankar',desc:'Notice breath, body, energy, resistance and the after-effect without forcing meaning.'},
 {id:'om',name:'Om',desc:'Attend to sound, vibration, silence and the return of thought.'},
 {id:'gratitude',name:'Gratitude',desc:'Receive this day, food and relationship without making gratitude a duty.'}
];
let state={entries:[]},selectedTags=new Set(),deferredPrompt;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&Array.isArray(x.entries))state=x}catch(e){console.warn(e)}}
function persist(){localStorage.setItem(STORE,JSON.stringify(state))}
function show(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));scrollTo({top:0,behavior:'smooth'});if(view==='review')renderEntries()}
function renderTags(){const host=$('#tagChoices');host.innerHTML='';TAGS.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='chip'+(selectedTags.has(t.id)?' selected':'');b.textContent=t.name;b.onclick=()=>{selectedTags.has(t.id)?selectedTags.delete(t.id):selectedTags.add(t.id);renderTags()};host.append(b)})}
function start(kind='free',practice='',period=''){resetForm();$('#kind').value=kind;$('#practice').value=practice||period;const map={before:['Before practice','What is present before beginning?','Notice intention, expectation, body and the one who wants an outcome.'],after:['After practice','What was directly known?','Describe sensations, feelings, thoughts and silence before interpreting them.'],gratitude:[period+' gratitude','What is being received now?','Name what is given: life, food, people, earth, effort. Let gratitude be felt rather than performed.'],free:['Free writing','What is true in experience now?','Write what was actually seen, felt or heard. Leave conclusions aside for a moment.']};const a=map[kind]||map.free;$('#formKicker').textContent=a[0];$('#formTitle').textContent=a[1];$('#guidedPrompt').textContent=a[2];if(practice==='Gauri Shankar')selectedTags.add('gauri-shankar');if(practice==='Om')selectedTags.add('om');if(kind==='gratitude')selectedTags.add('gratitude');renderTags();show('write')}
function resetForm(){$('#entryForm').reset();$('#entryId').value='';selectedTags.clear();renderTags();$('#saveStatus').textContent='';$('#formKicker').textContent='Free writing';$('#formTitle').textContent='What is true in experience now?';$('#guidedPrompt').textContent='Write what was actually seen, felt or heard. Leave conclusions aside for a moment.'}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function saveEntry(e){e.preventDefault();const id=$('#entryId').value||crypto.randomUUID();const old=state.entries.find(x=>x.id===id);const entry={id,created:old?.created||new Date().toISOString(),updated:new Date().toISOString(),kind:$('#kind').value,practice:$('#practice').value.trim(),direct:$('#direct').value.trim(),story:$('#story').value.trim(),beforeStory:$('#beforeStory').value.trim(),nextStep:$('#nextStep').value.trim(),tags:[...selectedTags]};state.entries=state.entries.filter(x=>x.id!==id);state.entries.unshift(entry);persist();$('#saveStatus').textContent='Saved on this device.';setTimeout(()=>show('review'),500)}
function edit(id){const x=state.entries.find(e=>e.id===id);if(!x)return;resetForm();$('#entryId').value=x.id;$('#kind').value=x.kind;$('#practice').value=x.practice;$('#direct').value=x.direct;$('#story').value=x.story;$('#beforeStory').value=x.beforeStory;$('#nextStep').value=x.nextStep;selectedTags=new Set(x.tags);renderTags();$('#formKicker').textContent='Edit entry';$('#formTitle').textContent='Return to your own words';show('write')}
function removeOne(id){if(confirm('Delete this entry? This cannot be undone.')){state.entries=state.entries.filter(e=>e.id!==id);persist();renderEntries()}}
function renderEntries(filter='all'){const list=$('#entries');const rows=filter==='all'?state.entries:state.entries.filter(e=>e.tags.includes(filter));list.innerHTML='';rows.forEach(x=>{const t=x.tags.map(id=>TAGS.find(t=>t.id===id)?.name).filter(Boolean);const el=document.createElement('article');el.className='entry';el.innerHTML=`<div class="entry-head"><h3>${esc(x.practice||({'before':'Before practice','after':'After practice','gratitude':'Gratitude','free':'Free writing'}[x.kind]))}</h3><time>${new Date(x.created).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}</time></div><div class="tagline">${t.map(esc).join(' · ')}</div><p class="body">${esc(x.direct)}</p>${x.story||x.beforeStory||x.nextStep?`<details><summary>See the whole entry</summary>${x.story?`<p><b>The “I” story</b><br>${esc(x.story)}</p>`:''}${x.beforeStory?`<p><b>Before the story</b><br>${esc(x.beforeStory)}</p>`:''}${x.nextStep?`<p><b>Gentle next step</b><br>${esc(x.nextStep)}</p>`:''}</details>`:''}<div class="entry-actions"><button data-edit="${x.id}">Edit</button><button data-remove="${x.id}">Delete</button></div>`;list.append(el)});$('#empty').classList.toggle('hidden',rows.length>0);const counts=state.entries.reduce((a,e)=>{e.tags.forEach(t=>a[t]=(a[t]||0)+1);return a},{});const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];$('#summary').innerHTML=`<div class="stat"><b>${state.entries.length}</b><span>entries</span></div><div class="stat"><b>${state.entries.filter(e=>Date.now()-new Date(e.created)<7*864e5).length}</b><span>last 7 days</span></div><div class="stat"><b>${top?top[1]:0}</b><span>${top?esc(TAGS.find(t=>t.id===top[0])?.name||'thread'):'threads revisited'}</span></div>`}
function renderFilters(){const h=$('#filters');h.innerHTML='';[['all','All'],...TAGS.map(t=>[t.id,t.name])].forEach(([id,name],i)=>{const b=document.createElement('button');b.className='chip'+(i===0?' selected':'');b.textContent=name;b.onclick=()=>{$$('#filters .chip').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderEntries(id)};h.append(b)})}
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportText(){const out=state.entries.map(e=>`${new Date(e.created).toLocaleString()}\n${e.practice||e.kind}\nThreads: ${e.tags.map(id=>TAGS.find(t=>t.id===id)?.name).join(', ')}\n\nDirect experience\n${e.direct}\n\nWhat “I” claimed\n${e.story}\n\nBefore the story\n${e.beforeStory}\n\nNext step\n${e.nextStep}\n\n---`).join('\n\n');download(`witness-journal-${new Date().toISOString().slice(0,10)}.txt`,'text/plain',out)}
function importFile(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!Array.isArray(x.entries))throw Error();const valid=x.entries.every(e=>e.id&&e.created&&typeof e.direct==='string'&&Array.isArray(e.tags));if(!valid)throw Error();const map=new Map(state.entries.map(e=>[e.id,e]));x.entries.forEach(e=>map.set(e.id,e));state.entries=[...map.values()].sort((a,b)=>new Date(b.created)-new Date(a.created));persist();renderEntries();alert(`Imported ${x.entries.length} entries. Existing entries were kept.`);show('review')}catch(e){alert('That file is not a valid Witness Journal backup.')}};r.readAsText(file)}
$$('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start,b.dataset.practice||'',b.dataset.period||''));$('#entryForm').onsubmit=saveEntry;$('#clearForm').onclick=resetForm;$('#newEntry').onclick=()=>start();$('#entries').onclick=e=>{if(e.target.dataset.edit)edit(e.target.dataset.edit);if(e.target.dataset.remove)removeOne(e.target.dataset.remove)};$('#exportJson').onclick=()=>download(`witness-journal-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify({format:'witness-journal',version:1,exported:new Date().toISOString(),entries:state.entries},null,2));$('#exportText').onclick=exportText;$('#importJson').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$('#deleteAll').onclick=()=>{$('#confirm').classList.remove('hidden');$('#confirmText').value='';$('#confirmDelete').disabled=true};$('#cancelDelete').onclick=()=>$('#confirm').classList.add('hidden');$('#confirmText').oninput=e=>$('#confirmDelete').disabled=e.target.value!=='DELETE';$('#confirmDelete').onclick=()=>{state={entries:[]};persist();$('#confirm').classList.add('hidden');renderEntries();show('review')};
TAGS.forEach(t=>{const el=document.createElement('article');el.className='thread';el.innerHTML=`<h3>${esc(t.name)}</h3><p>${esc(t.desc)}</p>`;el.onclick=()=>{start();selectedTags.add(t.id);renderTags()};$('#threadList').append(el)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').classList.remove('hidden')});$('#install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#install').classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
load();renderTags();renderFilters();renderEntries();
